spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/postgres
    driver-class-name : org.postgresql.Driver
    username : postgres
    password : mypassword
eureka:
  client:
     enabled: true
  instance: http://localhost:9999

bestOne: Rachael mcAdams
